# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIMyrJlcHVpL5Konxa9Xn6a5fGgLsd63
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py

import tensorflow as tf
from tensorflow import keras
import PIL
import streamlit as st
import cv2
import numpy as np



model = keras.models.load_model("https://github.com/aishwaryabit1603/SE_Handwritten_OCR/blob/e1d8096561592fb9a8921fa5717690c6728d7e18/DenseNet121_model.h5")

st.title("Handwritten Character Recoginition")
st.header("Please upload your image here")

file=st.file_uploader(" ",type=['jpg','jpeg','png'])


if file is not None:
    image=PIL.Image.open(file).convert('RGB')
    st.image(image,use_column_width=True)

    file_arr = np.array(image)
    file_arr=cv2.resize(file_arr,(180,180))
    file_arr=file_arr/255

    file_arr = np.expand_dims(file_arr, axis=0)

    outcome = np.argmax(model.predict(file_arr))
    predicted_class = class_names[outcome]

    # Display the predicted class
    st.write("Predicted class:", predicted_class)

    # Display the corresponding image for the predicted class
    st.image(class_images[outcome], use_column_width=True)
